services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - "3030:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - get
      - delete
      - post
      - put
  backend:
    image: sarpsahinalp/exercise-3:latest
    container_name: backend
    ports:
      - "3035:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  get:
    image: sarpsahinalp/exercise-3:latest
    container_name: get
    ports:
      - "3031:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  delete:
    image: sarpsahinalp/exercise-3:latest
    container_name: delete
    ports:
      - "3032:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  post:
    image: sarpsahinalp/exercise-3:latest
    container_name: post
    ports:
      - "3033:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  put:
    image: sarpsahinalp/exercise-3:latest
    container_name: put
    ports:
      - "3034:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb